server {
    listen 80;
    index index.php index.html;

    root /var/www/public;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        # 🔥 SI ES UNA PETICIÓN PREFLIGHT (OPTIONS), LE RESPONDEMOS OK DE UNA VEZ
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://mother.test' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, X-CSRF-TOKEN' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Content-Length' 0;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            return 204;
        }

        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\..+)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # Pasar cabeceras CORS también a las respuestas de PHP
        add_header 'Access-Control-Allow-Origin' 'http://mother.test' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
    }
}
